version: '3.8'

services:
  db:
    image: postgres:17.4-alpine3.21

    container_name: pricing_db_service

    environment:
      POSTGRES_DB: ${POSTGRES_DB:-pricing_db}
      POSTGRES_USER: ${POSTGRES_USER:-pricing_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}

    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-pricing_user} -d ${POSTGRES_DB:-pricing_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes: {}
